Import from meteor-buildpack-horse

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -15,6 +15,9 @@ BPLOG_PREFIX="buildpack.nodejs"
 
 ### Configure directories
 
+# Get the path to dir one above this file.
+BUILDPACK_DIR=$(cd -P -- "$(dirname -- "$0")" && cd .. && pwd -P)
+
 BUILD_DIR=${1:-}
 CACHE_DIR=${2:-}
 ENV_DIR=${3:-}
@@ -175,12 +178,6 @@ install_bins() {
 header "Installing binaries" | output "$LOG_FILE"
 install_bins | output "$LOG_FILE"
 
-header "Installing meteor" | output "$LOG_FILE"
-METEOR_DIR="$CACHE_DIR/meteor"
-mkdir -p "$METEOR_DIR"
-curl -sS "https://install.meteor.com/" | HOME="$METEOR_DIR" /bin/sh
-export PATH="$METEOR_DIR/.meteor":$PATH
-
 restore_cache() {
   local cache_status cache_directories
 
@@ -227,6 +224,129 @@ restore_cache() {
 }
 
 restore_cache | output "$LOG_FILE"
+
+
+###############################################################################
+# copyright https://github.com/AdmitHub/meteor-buildpack-horse
+###############################################################################
+
+header "Installing meteor" | output "$LOG_FILE"
+
+if [ ! -d "$BUILD_DIR/.meteor" ]; then
+  echo "FATAL: Can't find meteor app."
+  exit 1
+fi
+
+# Where we will install meteor. Has to be outside the BUILD_DIR.
+METEOR_DIR="$CACHE_DIR/meteor"
+# Where we'll put things we compile.
+COMPILE_DIR_SUFFIX=".meteor/heroku_build"
+COMPILE_DIR="$BUILD_DIR"/"$COMPILE_DIR_SUFFIX"
+# Try to minimize meteor's printing, unless we're running verbosely.
+if [ -z "$BUILDPACK_VERBOSE" ]; then
+#  METEOR_PRETTY_OUTPUT=0
+fi
+
+# Create directories as needed.
+mkdir -p "$BUILD_DIR" "$METEOR_DIR"
+mkdir -p "$COMPILE_DIR" "$COMPILE_DIR/bin" "$COMPILE_DIR/lib"
+
+# Install the latest meteor, and rely on meteor to upgrade/downgrade itself to
+# the .meteor/release target.
+if [ -e "$METEOR_DIR/.meteor/meteor" ]; then
+  echo "-----> Existing meteor installation found, using it."
+else
+  echo "-----> Installing meteor"
+  curl -sS "https://install.meteor.com/" | HOME="$METEOR_DIR" /bin/sh
+fi
+# Function to execute meteor with proper HOME.
+function METEOR {
+  ARGS=$@
+  HOME="$METEOR_DIR" "$METEOR_DIR/.meteor/meteor" $ARGS
+}
+
+#
+# Build the meteor app!
+#
+
+# Change into the project directory. Once we're there, 'meteor' commands will
+# run with the context of the target release (project .meteor/release) rather
+# than the "latest" that is installed by install.meteor.com.
+cd "$BUILD_DIR"
+
+echo "-----> Target Meteor version: `METEOR --version`"
+
+# Identify the npm/node to use. We need to copy the node binary out to get the
+# correct version in the built slug (e.g. 0.10.x for Meteor<1.4, 4.x for
+# Meteor>=1.4).  We can't copy the whole meteor world because that's too large
+# (Issue #125).
+
+# Query node for its own path. As long as the Meteor version we got from
+# install.meteor.com is >=1.3, "meteor node" is available, even if the target
+# release predates that feature.
+METEOR_NODE=`METEOR node -e "process.stdout.write(process.execPath)"`
+# Assume npm is in the same dir as node.
+METEOR_NPM="`dirname "$METEOR_NODE"`/npm"
+
+if [ -z "$METEOR_NPM" ] || [ -z "$METEOR_NODE" ] ; then
+  echo "FATAL: Can't find npm/node within meteor bundle. This is a bug. Please open an issue at https://github.com/AdmitHub/meteor-buildpack-horse.";
+  exit 1
+fi
+
+# Copy node into place for production.
+NODE="$COMPILE_DIR"/bin/node
+cp "$METEOR_NODE" "$NODE"
+chmod a+x "$NODE"
+
+# Add npm and node path so that 1.4's npm-rebuild.js will function.
+PATH="$METEOR_DIR/.meteor:`dirname $METEOR_NPM`:$COMPILE_DIR/bin:$PATH"
+
+echo "-----> Using node: `$NODE --version`"
+echo "----->    and npm: `$METEOR_NPM --version`"
+
+# If we use npm on root, run npm install.  Don't use `--production` here, as we
+# may need devDependencies (e.g. webpack) in order to build the meteor app.
+if [ -e "$BUILD_DIR"/package.json ]; then
+  $METEOR_NPM install
+fi
+
+# Now on to bundling. Don't put the bundle in $BUILD_DIR during
+# bundling, or it will recurse, trying to bundle up its own bundling.
+
+echo "-----> Building Meteor app with ROOT_URL: $ROOT_URL"
+BUNDLE_DEST=`mktemp -d "$BUILDPACK_DIR/build-XXXX"`
+
+# The actual invocation of `meteor build`!
+METEOR build $BUILD_OPTIONS --server $ROOT_URL --server-only --directory $BUNDLE_DEST
+
+echo "-----> Moving built slug to $COMPILE_DIR/app"
+mv $BUNDLE_DEST/bundle "$COMPILE_DIR/app"
+rmdir $BUNDLE_DEST
+
+# Run npm install on the built slug; only for '--production' dependencies.
+echo "-----> Installing npm production dependencies on built slug"
+if [ -e "$COMPILE_DIR"/app/programs/server/package.json ]; then
+  cd "$COMPILE_DIR"/app/programs/server
+  $METEOR_NPM install --production
+  cd "$BUILD_DIR"
+fi
+
+#
+# Environment
+#
+# Add an export of PATH which includes our compile dir, etc.
+echo "-----> Adding PATH environment"
+mkdir -p "$BUILD_DIR"/.profile.d
+cat > "$BUILD_DIR"/.profile.d/path.sh <<EOF
+  #!/bin/sh
+  export PATH=\$HOME/$COMPILE_DIR_SUFFIX/bin:\$PATH
+  export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:\$HOME/$COMPILE_DIR_SUFFIX/lib
+EOF
+
+echo "-----> Clearing cache dir."
+rm -rf $METEOR_DIR
+
+###############################################################################
 
 build_dependencies() {
   local cache_status start
